services:
  - type: web
    name: trabajo-final-backend
    env: python
    rootDir: app
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    pythonVersion: 3.12.4
